### PR TITLE
MIST-465 clustered hw

### PR DESCRIPTION
**Pull request by mmlb**
[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-os/118)

### CODE REVIEW

**Comment by trisk** [comment]
<sup>**[board/mistify/rootfs_overlay/etc/pre-init.d/net-init.sh, line 80 \[r4\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/118#-JtA6gL00f8sZGvcEJ4W)** ([raw file](https://github.com/mistifyio/mistify-os/blob/9312ed1b627741724b66d1ecb47681e3ef893658/board/mistify/rootfs_overlay/etc/pre-init.d/net-init.sh#L80)):</sup>
We release the leases on all devs here, are we guaranteed to only have one active?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/118)

**Comment by mmlb** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[board/mistify/rootfs_overlay/etc/pre-init.d/net-init.sh, line 80 \[r4\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/118#-JtA6gL00f8sZGvcEJ4W)** ([raw file](https://github.com/mistifyio/mistify-os/blob/9312ed1b627741724b66d1ecb47681e3ef893658/board/mistify/rootfs_overlay/etc/pre-init.d/net-init.sh#L80)):</sup>
not really, but there's a whole slew of places where it's assumed that only 1 is active. Changing this script to handle multiple interfaces that could give dhcp should be left to another card. Part of the MVP on HW docs will note the limitations, 1 active interface will be on there.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/118)

**Comment by trisk** [comment]
<sup>**[board/mistify/rootfs_overlay/etc/dhclient-exit-hooks, line 19 \[r4\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/118#-JtA7YfF0C9HN_HOP6Af)** ([raw file](https://github.com/mistifyio/mistify-os/blob/9312ed1b627741724b66d1ecb47681e3ef893658/board/mistify/rootfs_overlay/etc/dhclient-exit-hooks#L19)):</sup>
Should be`=`, rather than `==`.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/118)

**Comment by trisk** [comment]
<sup>**[board/mistify/rootfs_overlay/etc/dhclient-exit-hooks, line 4 \[r4\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/118#-JtA78ZW5e9YHdop_Tpy)** ([raw file](https://github.com/mistifyio/mistify-os/blob/9312ed1b627741724b66d1ecb47681e3ef893658/board/mistify/rootfs_overlay/etc/dhclient-exit-hooks#L4)):</sup>
Better to have quotes around $MISTIFY_IFSTATE here for empty string (or use the old-style `if [ x$... = x ]`). Also, only need single brackets.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/118)

**Comment by trisk** [comment]
<sup>**[board/mistify/rootfs_overlay/etc/dhclient-exit-hooks, line 19 \[r4\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/118#-JtA7YfF0C9HN_HOP6Af)** ([raw file](https://github.com/mistifyio/mistify-os/blob/9312ed1b627741724b66d1ecb47681e3ef893658/board/mistify/rootfs_overlay/etc/dhclient-exit-hooks#L19)):</sup>
I see the interpreter path has been changed, so I guess that's okay too.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/118)

**Comment by trisk** [comment]
Reviewed 3 of 5 files at r1, 3 of 4 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/118)

**Comment by mmlb** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[board/mistify/rootfs_overlay/etc/dhclient-exit-hooks, line 4 \[r4\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/118#-JtA78ZW5e9YHdop_Tpy)** ([raw file](https://github.com/mistifyio/mistify-os/blob/9312ed1b627741724b66d1ecb47681e3ef893658/board/mistify/rootfs_overlay/etc/dhclient-exit-hooks#L4)):</sup>
I prefer the `-z` to old hacks, but I might as well stay in line with the rest of the file.

---

<sup>**[board/mistify/rootfs_overlay/etc/dhclient-exit-hooks, line 19 \[r4\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/118#-JtA7YfF0C9HN_HOP6Af)** ([raw file](https://github.com/mistifyio/mistify-os/blob/9312ed1b627741724b66d1ecb47681e3ef893658/board/mistify/rootfs_overlay/etc/dhclient-exit-hooks#L19)):</sup>
Yeah, the interpreter change doesn't really matter since this file is being sourced from `/bin/sh` script, which on mistify-os is really bash, but I'll change back. I originally changed since I forgot to quote the var and was getting `-sh: [: too many argument` error and figured I'd just use bash array.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/118)

**Comment by trisk** [comment]
<sup>**[board/mistify/rootfs_overlay/etc/dhclient-exit-hooks, line 1 \[r6\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/118#-JtAJVu2eT-9142R1OI1)** ([raw file](https://github.com/mistifyio/mistify-os/blob/bb20aaa293d678624783e3b15a05fd02b541ce95/board/mistify/rootfs_overlay/etc/dhclient-exit-hooks#L1)):</sup>
`==` instead of `=` for string compare is actually a bashism.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/118)

**Comment by trisk** [comment]
Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/118)

**Comment by mmlb** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[board/mistify/rootfs_overlay/etc/dhclient-exit-hooks, line 1 \[r6\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/118#-JtAJVu2eT-9142R1OI1)** ([raw file](https://github.com/mistifyio/mistify-os/blob/bb20aaa293d678624783e3b15a05fd02b541ce95/board/mistify/rootfs_overlay/etc/dhclient-exit-hooks#L1)):</sup>
doh, yeah missed that

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/118)

**Comment by mmlb** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[board/mistify/rootfs_overlay/etc/dhclient-exit-hooks, line 1 \[r6\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/118#-JtAJVu2eT-9142R1OI1)** ([raw file](https://github.com/mistifyio/mistify-os/blob/bb20aaa293d678624783e3b15a05fd02b541ce95/board/mistify/rootfs_overlay/etc/dhclient-exit-hooks#L1)):</sup>
fixed

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/118)

**Comment by mmlb** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[board/mistify/rootfs_overlay/etc/dhclient-exit-hooks, line 16 \[r7\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/118#-JtAKGw6hYKURKxDJh4O)** ([raw file](https://github.com/mistifyio/mistify-os/blob/8ee5bde6eb107d781ee89260ec75113381549d52/board/mistify/rootfs_overlay/etc/dhclient-exit-hooks#L16)):</sup>
damn missed it here too

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/118)

**Comment by mmlb** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[board/mistify/rootfs_overlay/etc/dhclient-exit-hooks, line 16 \[r7\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/118#-JtAKGw6hYKURKxDJh4O)** ([raw file](https://github.com/mistifyio/mistify-os/blob/8ee5bde6eb107d781ee89260ec75113381549d52/board/mistify/rootfs_overlay/etc/dhclient-exit-hooks#L16)):</sup>
fixed now

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/118)

**Comment by mmlb** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[board/mistify/rootfs_overlay/etc/dhclient-exit-hooks, line 16 \[r7\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/118#-JtAKGw6hYKURKxDJh4O)** ([raw file](https://github.com/mistifyio/mistify-os/blob/8ee5bde6eb107d781ee89260ec75113381549d52/board/mistify/rootfs_overlay/etc/dhclient-exit-hooks#L16)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/118)

**Comment by mmlb** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[board/mistify/rootfs_overlay/etc/dhclient-exit-hooks, line 16 \[r7\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/118#-JtAKGw6hYKURKxDJh4O)** ([raw file](https://github.com/mistifyio/mistify-os/blob/8ee5bde6eb107d781ee89260ec75113381549d52/board/mistify/rootfs_overlay/etc/dhclient-exit-hooks#L16)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/118)

**Comment by trisk** [comment]
Reviewed 1 of 1 files at r8.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/118)

**Comment by daleghent** [comment]
Reviewed 4 of 5 files at r3, 1 of 1 files at r8.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/118)

**Comment by daleghent** [comment]
Reviewed 3 of 5 files at r3, 2 of 2 files at r9.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/118)

**Comment by trisk** [comment]
<sup>**[board/mistify/rootfs_overlay/root/cluster-init, line 14 \[r9\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/118#-Jt_RMCg4Kn1i1-RFqKu)** ([raw file](https://github.com/mistifyio/mistify-os/blob/c503c1a5c0f3a131cd13a1b3553dd8e0c28bf283/board/mistify/rootfs_overlay/root/cluster-init#L14)):</sup>
I suspect there's some `exec 2> tee >(systemd-cat -t cluster-init-err)` ish thing way that is less gross, but this is okay.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/118)

**Comment by trisk** [comment]
Reviewed 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/118)

**Comment by mmlb** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[board/mistify/rootfs_overlay/root/cluster-init, line 14 \[r9\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/118#-Jt_RMCg4Kn1i1-RFqKu)** ([raw file](https://github.com/mistifyio/mistify-os/blob/c503c1a5c0f3a131cd13a1b3553dd8e0c28bf283/board/mistify/rootfs_overlay/root/cluster-init#L14)):</sup>
hmm, yeah I remember doing it that way earlier at some earlier point but split out to functions for some reason... meh I can update later, but I really want this pr done with.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/118)

**Comment by mmlb** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[board/mistify/rootfs_overlay/root/cluster-init, line 14 \[r9\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/118#-Jt_RMCg4Kn1i1-RFqKu)** ([raw file](https://github.com/mistifyio/mistify-os/blob/c503c1a5c0f3a131cd13a1b3553dd8e0c28bf283/board/mistify/rootfs_overlay/root/cluster-init#L14)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/118)

**Comment by StevenIsaacs** [comment]
Reviewed 3 of 5 files at r3, 2 of 2 files at r9.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[board/mistify/rootfs_overlay/etc/dhclient-exit-hooks, line 1 \[r9\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/118#-Jtcal0aX_mg7_myDUsu)** ([raw file](https://github.com/mistifyio/mistify-os/blob/c503c1a5c0f3a131cd13a1b3553dd8e0c28bf283/board/mistify/rootfs_overlay/etc/dhclient-exit-hooks#L1)):</sup>
test ([) provides the -z option for testing for empty strings. Is there a reason it wasn't used in this script? This works but just curious.

---

<sup>**[board/mistify/rootfs_overlay/etc/dhclient-exit-hooks, line 23 \[r9\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/118#-JtcbnQpGkyXlMQIxiH9)** ([raw file](https://github.com/mistifyio/mistify-os/blob/c503c1a5c0f3a131cd13a1b3553dd8e0c28bf283/board/mistify/rootfs_overlay/etc/dhclient-exit-hooks#L23)):</sup>
Also, test provides the -n option for testing non-empty strings.

---

<sup>**[board/mistify/rootfs_overlay/root/cluster-init, line 95 \[r9\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/118#-JtcieZfIEFFhQbdwbO3)** ([raw file](https://github.com/mistifyio/mistify-os/blob/c503c1a5c0f3a131cd13a1b3553dd8e0c28bf283/board/mistify/rootfs_overlay/root/cluster-init#L95)):</sup>
Shouldn't this include ETCD_DATA_DIR? This is the original:
```
##
## options for etcd.service
## etcd uses these for configuration:
## https://github.com/coreos/etcd/blob/master/Documentation/configuration.md
##

ETCD_DATA_DIR=/mistify/data/etcd
```

---

<sup>**[board/mistify/rootfs_overlay/root/cluster-init-config, line 15 \[r9\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/118#-JtcklkqH2WZ0AZoG0iZ)** ([raw file](https://github.com/mistifyio/mistify-os/blob/c503c1a5c0f3a131cd13a1b3553dd8e0c28bf283/board/mistify/rootfs_overlay/root/cluster-init-config#L15)):</sup>
I like these new values.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/118)

**Comment by mmlb** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[board/mistify/rootfs_overlay/etc/dhclient-exit-hooks, line 1 \[r9\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/118#-Jtcal0aX_mg7_myDUsu)** ([raw file](https://github.com/mistifyio/mistify-os/blob/c503c1a5c0f3a131cd13a1b3553dd8e0c28bf283/board/mistify/rootfs_overlay/etc/dhclient-exit-hooks#L1)):</sup>
Not much of a reason, I normally use -z/-n type tests but I initially copied one or two of these from `dhclient-script` which uses this form and so I kept it up when I added other tests.

---

<sup>**[board/mistify/rootfs_overlay/etc/dhclient-exit-hooks, line 23 \[r9\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/118#-JtcbnQpGkyXlMQIxiH9)** ([raw file](https://github.com/mistifyio/mistify-os/blob/c503c1a5c0f3a131cd13a1b3553dd8e0c28bf283/board/mistify/rootfs_overlay/etc/dhclient-exit-hooks#L23)):</sup>
see above

---

<sup>**[board/mistify/rootfs_overlay/root/cluster-init, line 95 \[r9\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/118#-JtcieZfIEFFhQbdwbO3)** ([raw file](https://github.com/mistifyio/mistify-os/blob/c503c1a5c0f3a131cd13a1b3553dd8e0c28bf283/board/mistify/rootfs_overlay/root/cluster-init#L95)):</sup>
Nope, that is still provided from the service file and is valid there is no need to override that value.

---

<sup>**[board/mistify/rootfs_overlay/root/cluster-init-config, line 15 \[r9\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/118#-JtcklkqH2WZ0AZoG0iZ)** ([raw file](https://github.com/mistifyio/mistify-os/blob/c503c1a5c0f3a131cd13a1b3553dd8e0c28bf283/board/mistify/rootfs_overlay/root/cluster-init-config#L15)):</sup>
yeah this should make your test life much easier. oh and btw there is no longer a need to do your double boot of the vm hack for tests. Will follow up on slack.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/118)

**Pull request merged**
