### PR TITLE
Use prebuilt toolchain

### PR DESCRIPTION
**Pull request by rizvfe00**
[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-os/149)

### CODE REVIEW

**Comment by StevenIsaacs** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

<sup>**[scripts/install-toolchain.sh, line 21 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/149#-K-tu4TMxW8lUO69UFth)** ([raw file](https://github.com/mistifyio/mistify-os/blob/976ef9e5c390f62c88f2f2288dddb16d91f3c3e0/scripts/install-toolchain.sh#L21)):</sup>
This needs to be updated to match master (it's now a hash instead of a release version).


---

<sup>**[scripts/install-toolchain.sh, line 22 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/149#-K-tttNrYD_XVKB6mtOw)** ([raw file](https://github.com/mistifyio/mistify-os/blob/976ef9e5c390f62c88f2f2288dddb16d91f3c3e0/scripts/install-toolchain.sh#L22)):</sup>
What's this version?


---

<sup>**[scripts/Makefile-toolchain, line 8 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/149#-K-tuKXsKljsr1_7XsDd)** ([raw file](https://github.com/mistifyio/mistify-os/blob/976ef9e5c390f62c88f2f2288dddb16d91f3c3e0/scripts/Makefile-toolchain#L8)):</sup>
Should this be updated?


---

<sup>**[scripts/Makefile-toolchain, line 12 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/149#-K-tsnEG17fXU2Ab7oRi)** ([raw file](https://github.com/mistifyio/mistify-os/blob/976ef9e5c390f62c88f2f2288dddb16d91f3c3e0/scripts/Makefile-toolchain#L12)):</sup>
mistify_defconfig is for buildroot. The correct config file for the toolchain is mistify-tc.config


---

<sup>**[scripts/Makefile-toolchain, line 53 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/149#-K-tuUbfyimDrzbcmmBZ)** ([raw file](https://github.com/mistifyio/mistify-os/blob/976ef9e5c390f62c88f2f2288dddb16d91f3c3e0/scripts/Makefile-toolchain#L53)):</sup>
This as some point may need to support config variants. The install script doesn't at the moment.


---

<sup>**[scripts/Makefile-toolchain, line 93 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/149#-K-tqZhXhRZ1vJMX_PcX)** ([raw file](https://github.com/mistifyio/mistify-os/blob/976ef9e5c390f62c88f2f2288dddb16d91f3c3e0/scripts/Makefile-toolchain#L93)):</sup>
Need newline.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/149)

**Comment by rizvfe00** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

<sup>**[scripts/install-toolchain.sh, line 21 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/149#-K-tu4TMxW8lUO69UFth)** ([raw file](https://github.com/mistifyio/mistify-os/blob/976ef9e5c390f62c88f2f2288dddb16d91f3c3e0/scripts/install-toolchain.sh#L21)):</sup>
Need to merge with master


---

<sup>**[scripts/install-toolchain.sh, line 22 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/149#-K-tttNrYD_XVKB6mtOw)** ([raw file](https://github.com/mistifyio/mistify-os/blob/976ef9e5c390f62c88f2f2288dddb16d91f3c3e0/scripts/install-toolchain.sh#L22)):</sup>
This is a pre-built toolchain version in S3.  It's designed to account for the possibility that we fork the crosstool-ng repo.  We can align it with the exact crosstool-ng version for now.


---

<sup>**[scripts/Makefile-toolchain, line 8 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/149#-K-tuKXsKljsr1_7XsDd)** ([raw file](https://github.com/mistifyio/mistify-os/blob/976ef9e5c390f62c88f2f2288dddb16d91f3c3e0/scripts/Makefile-toolchain#L8)):</sup>
This a sensible default for compiling locally.  It gets overidden by the call from install-toolchain.sh.  This was originally designed to be a standalone buildscript in the crosstool fork.  I think we should leave it this way, it works for the way we have it now in mistify-os (buildmistify.sh) and if we forked we could literally drop this file inside the repo and it would build.


---

<sup>**[scripts/Makefile-toolchain, line 12 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/149#-K-tsnEG17fXU2Ab7oRi)** ([raw file](https://github.com/mistifyio/mistify-os/blob/976ef9e5c390f62c88f2f2288dddb16d91f3c3e0/scripts/Makefile-toolchain#L12)):</sup>
This is also a sensible default.  It gets overriden during the make call we can change the default to something else.


---

<sup>**[scripts/Makefile-toolchain, line 53 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/149#-K-tuUbfyimDrzbcmmBZ)** ([raw file](https://github.com/mistifyio/mistify-os/blob/976ef9e5c390f62c88f2f2288dddb16d91f3c3e0/scripts/Makefile-toolchain#L53)):</sup>
Need to talk to you a bit more about this


---

<sup>**[scripts/Makefile-toolchain, line 93 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/149#-K-tqZhXhRZ1vJMX_PcX)** ([raw file](https://github.com/mistifyio/mistify-os/blob/976ef9e5c390f62c88f2f2288dddb16d91f3c3e0/scripts/Makefile-toolchain#L93)):</sup>
Added


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/149)

**Comment by StevenIsaacs** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

<sup>**[scripts/install-toolchain.sh, line 147 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/149#-K-uZdWoFzLP1OMUUpnR)** ([raw file](https://github.com/mistifyio/mistify-os/blob/976ef9e5c390f62c88f2f2288dddb16d91f3c3e0/scripts/install-toolchain.sh#L147)):</sup>
Is PWD always pointing to the correct location at this point?  The variable $toolchaindir can point to anywhere. This will work only for the default value.
It would be better to not cd and instead use the -C option with make. e.g. make -f scripts/Makefile-toolchain  -C $toolchaindir $makeargs OR, at least copy and then cd.


---

<sup>**[scripts/Makefile-toolchain, line 8 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/149#-K-tuKXsKljsr1_7XsDd)** ([raw file](https://github.com/mistifyio/mistify-os/blob/976ef9e5c390f62c88f2f2288dddb16d91f3c3e0/scripts/Makefile-toolchain#L8)):</sup>
I know this gets overridden. It's confusing to see 1.20.0 instead of at least 1.21.0. We need to be careful about confusing versions that are similar to ct-ng but don't represent the same thing.


---

<sup>**[scripts/Makefile-toolchain, line 12 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/149#-K-tsnEG17fXU2Ab7oRi)** ([raw file](https://github.com/mistifyio/mistify-os/blob/976ef9e5c390f62c88f2f2288dddb16d91f3c3e0/scripts/Makefile-toolchain#L12)):</sup>
I know this is overridden by the calling script. This is NOT a sensible default. mistify_defconfig is for buildroot not crosstools-ng. A sensible default is mistify-tc.config.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/149)

**Comment by rizvfe00** [comment]
Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

<sup>**[scripts/install-toolchain.sh, line 147 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/149#-K-uZdWoFzLP1OMUUpnR)** ([raw file](https://github.com/mistifyio/mistify-os/blob/976ef9e5c390f62c88f2f2288dddb16d91f3c3e0/scripts/install-toolchain.sh#L147)):</sup>
Good point will change that


---

<sup>**[scripts/Makefile-toolchain, line 8 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/149#-K-tuKXsKljsr1_7XsDd)** ([raw file](https://github.com/mistifyio/mistify-os/blob/976ef9e5c390f62c88f2f2288dddb16d91f3c3e0/scripts/Makefile-toolchain#L8)):</sup>
Will update it to 1.21.0, I believe we were on 1.20.0 when it was written.


---

<sup>**[scripts/Makefile-toolchain, line 12 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/149#-K-tsnEG17fXU2Ab7oRi)** ([raw file](https://github.com/mistifyio/mistify-os/blob/976ef9e5c390f62c88f2f2288dddb16d91f3c3e0/scripts/Makefile-toolchain#L12)):</sup>
Will update to mistify-tc.config


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/149)

**Comment by StevenIsaacs** [comment]
Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[scripts/install-toolchain.sh, line 22 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/149#-K-tttNrYD_XVKB6mtOw)** ([raw file](https://github.com/mistifyio/mistify-os/blob/976ef9e5c390f62c88f2f2288dddb16d91f3c3e0/scripts/install-toolchain.sh#L22)):</sup>
After thinking about this the ct-ng version on which the prebuilt is based should be part of the name and then add/extend with our version. e.g. If ct-ng version is: 1.21.0 and the prebuild is 15 then 1.21.0-15. This will also work when using a hash instead of a version for the ct-ng repo (which is what is currently being used).


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/149)

**Comment by StevenIsaacs** [comment]
Reviewed 1 of 4 files at r1, 1 of 3 files at r2.
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/149)

**Comment by rizvfe00** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[scripts/install-toolchain.sh, line 22 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/149#-K-tttNrYD_XVKB6mtOw)** ([raw file](https://github.com/mistifyio/mistify-os/blob/976ef9e5c390f62c88f2f2288dddb16d91f3c3e0/scripts/install-toolchain.sh#L22)):</sup>
I set it to use the branch/tag we checkout the toolchain repo on this works in both cases version #'s or revisions.


---

<sup>**[scripts/Makefile-toolchain, line 53 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/149#-K-tuUbfyimDrzbcmmBZ)** ([raw file](https://github.com/mistifyio/mistify-os/blob/976ef9e5c390f62c88f2f2288dddb16d91f3c3e0/scripts/Makefile-toolchain#L53)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/149)

**Pull request merged**
