### PR TITLE
Mist 333 - SDK

### PR DESCRIPTION
**Pull request by StevenIsaacs**
This is a major revision which adds development capability to Mistify-OS. There are now two variants, *base* and *sdk* either of which can be specified using the `--variant` option with *buildmistify*. 

Major changes include:
* The *mistifyio* fork of *crosstools-ng* is now required and is the default in order to support multilib which is needed for generating ISOs. The required and default branch is *glibc-multilib-sdk* (based upon prior work by trisk). A config file to enable multilib, *configs/mistify-tc-multilib.config*, has been added and is selected by default. This is compatible with both the *sdk* and *base* variants and doesn't need to change.
* A *buildroot* configuration variant, *variants/sdk-mistify_defconfig* has been added. This enables features and selects packages needed for the SDK version of Mistify-OS. This also selects a custom *busybox* configuration file, *configs/mistify-busybox-sdk.config*, which adds tools for creating and managing users in the Mistify-OS SDK environment.
* A number of packages have been added to support builds in the Mistify-OS environment. These are all located in a *menuconfig* sub menu named SDK and are enabled by the *sdk* variant.
* The *mistify-post-build* script has been modified to make changes to the target rootfs to support the SDK. This occurs only when the *sdk* variant is being built and is triggered by a config option in the *sdk* variant of the defconfig (buildroot config file).

**NOTE:** Parallel changes have been made to the Robot Framework scripts in the *mistify-test* repo to verify local SDK builds.

**NOTE:** The Jenkins jobs running container based builds using Jenkins slaves on *dev-2* need to be updated to use the correct toolchain versions and the master branch of the *mistify-os* repo after this PR has been merged into the master branch.

There are a few cleanup changes currently being held back because this has been build tested both locally and using Jenkins. Also, dev-4 is running a Jenkins based build of the SDK which was then used to build both the *base* and *sdk* variants of Mistify-OS. The cleanup changes are being held back because of the time involved in verifying the changes.

Docs to follow...

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-os/152)

### CODE REVIEW

**Comment by daleghent** [comment]
Reviewed 22 of 28 files at r1, 1 of 4 files at r2, 1 of 1 files at r4, 3 of 6 files at r5, 7 of 7 files at r6, 3 of 3 files at r7.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/152)

**Comment by mmlb** [comment]
Reviewed 22 of 28 files at r1, 1 of 4 files at r2, 1 of 1 files at r4, 3 of 6 files at r5, 7 of 7 files at r6, 3 of 3 files at r7.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[package/mistify/perl-forks/Config.in, line 4 \[r7\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/152#-K2sbT7W8SuJw-D4pxDv)** ([raw file](https://github.com/mistifyio/mistify-os/blob/a14eb0c6f8af2365f30a4548cc6190ea93992eee/package/mistify/perl-forks/Config.in#L4)):</sup>
/treading/threading/


---

<sup>**[package/mistify/sdk-automake/Config.in, line 6 \[r7\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/152#-K2sc15xFKDbUJdqVOsf)** ([raw file](https://github.com/mistifyio/mistify-os/blob/a14eb0c6f8af2365f30a4548cc6190ea93992eee/package/mistify/sdk-automake/Config.in#L6)):</sup>
drop the '


---

<sup>**[package/mistify/sdk-gcc/sdk-gcc.mk, line 25 \[r7\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/152#-K2scaryFYoXRXJn-MnK)** ([raw file](https://github.com/mistifyio/mistify-os/blob/a14eb0c6f8af2365f30a4548cc6190ea93992eee/package/mistify/sdk-gcc/sdk-gcc.mk#L25)):</sup>
I believe we don't really need go support in gcc. You can remove it you want.


---

<sup>**[package/mistify/sdk-overrides/sdk-overrides.mk, line 27 \[r7\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/152#-K2sdO4eJb5NCsHzVlTy)** ([raw file](https://github.com/mistifyio/mistify-os/blob/a14eb0c6f8af2365f30a4548cc6190ea93992eee/package/mistify/sdk-overrides/sdk-overrides.mk#L27)):</sup>
/otherhand/other hand/


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/152)

**Comment by StevenIsaacs** [comment]
Review status: 34 of 37 files reviewed at latest revision, 1 unresolved discussion.

---

<sup>**[package/mistify/sdk-gcc/sdk-gcc.mk, line 25 \[r7\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/152#-K2scaryFYoXRXJn-MnK)** ([raw file](https://github.com/mistifyio/mistify-os/blob/a14eb0c6f8af2365f30a4548cc6190ea93992eee/package/mistify/sdk-gcc/sdk-gcc.mk#L25)):</sup>
This was in case was needed to build go 1.4. You could be right but didn't go back to be sure. Because it would trigger another round of testing I'll hang on to this one.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/152)

**Comment by mmlb** [comment]
Reviewed 3 of 3 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/152)

**Pull request merged**
