### PR TITLE
Mist 542 kernel rebuilds

### PR DESCRIPTION
**Pull request by StevenIsaacs**
This corrects a problem which was triggering a build of the kernel on every run of buildmistify. While at it I changed a command line option to be consistent with its corresponding variable.

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-os/142)

### CODE REVIEW

**Comment by TauZero** [comment]
Reviewed 2 of 2 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/142)

**Comment by mmlb** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[buildmistify, line 604 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/142#-JxGzvbKjwz7qfNJyrSs)** ([raw file](https://github.com/mistifyio/mistify-os/blob/4bdb9f764f01635be422bc66646c6ceb9c8ec697/buildmistify#L604)):</sup>
I'm not seeing where this variable is defined is it set in one of the supporting scripts?

---

<sup>**[buildmistify, line 713 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/142#-JxH-TVH_lM1vQ3h2x4w)** ([raw file](https://github.com/mistifyio/mistify-os/blob/4bdb9f764f01635be422bc66646c6ceb9c8ec697/buildmistify#L713)):</sup>
Why not add this block to the $logfile ala

```cat << EOF | tee $logfile
...
EOF```?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/142)
<!-- Sent from Reviewable.io -->

**Comment by mmlb** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/142)

**Comment by StevenIsaacs** [comment]
<sup>**[buildmistify, line 604 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/142#-JxGzvbKjwz7qfNJyrSs)** ([raw file](https://github.com/mistifyio/mistify-os/blob/4bdb9f764f01635be422bc66646c6ceb9c8ec697/buildmistify#L604)):</sup>
Good catch. Forgot that line when I removed a hack I did to uncover some detail from buildroot. I'll remove the line and push again.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/142)

**Comment by StevenIsaacs** [comment]
<sup>**[buildmistify, line 713 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/142#-JxH-TVH_lM1vQ3h2x4w)** ([raw file](https://github.com/mistifyio/mistify-os/blob/4bdb9f764f01635be422bc66646c6ceb9c8ec697/buildmistify#L713)):</sup>
You mean to the console output and the log file.  Yeah that might be useful.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/142)

**Comment by mmlb** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/142)

**Pull request merged**
