### PR TITLE
MIST-475 Image Service Support

### PR DESCRIPTION
**Pull request by TauZero**
Add package for mistify-image-service and update the hash/version on related packages

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-os/109)

### CODE REVIEW

**Comment by mmlb** [comment]
Waiting for build to verify all is ok

---

Review status: 7 of 9 files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- package/mistify/lochness-ansible/lochness-ansible.mk @ r1
- package/mistify/lochness/lochness.mk @ r1
- package/mistify/mistify-agent-docker/mistify-agent-docker.mk @ r1
- package/mistify/mistify-agent-image/mistify-agent-image.mk @ r1
- package/mistify/mistify-agent/mistify-agent.mk @ r1
- package/mistify/mistify-image-service/Config.in @ r1
- package/mistify/mistify-image-service/mistify-image-service.mk @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/109)

**Comment by trisk** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- Config.in @ r2
- configs/mistify_defconfig @ r2
- package/mistify/lochness-ansible/lochness-ansible.mk @ r1
- package/mistify/lochness/lochness.mk @ r1
- package/mistify/mistify-agent-docker/mistify-agent-docker.mk @ r1
- package/mistify/mistify-agent-image/mistify-agent-image.mk @ r1
- package/mistify/mistify-agent/mistify-agent.mk @ r1
- package/mistify/mistify-image-service/Config.in @ r1
- package/mistify/mistify-image-service/mistify-image-service.mk @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/109)

**Comment by mmlb** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- Config.in @ r2
- configs/mistify_defconfig @ r2
- package/mistify/lochness-ansible/lochness-ansible.mk @ r1
- package/mistify/lochness/lochness.mk @ r1
- package/mistify/mistify-agent-docker/mistify-agent-docker.mk @ r1
- package/mistify/mistify-agent-image/mistify-agent-image.mk @ r1
- package/mistify/mistify-agent/mistify-agent.mk @ r1
- package/mistify/mistify-image-service/Config.in @ r1
- package/mistify/mistify-image-service/mistify-image-service.mk @ r1

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/109)

**Comment by mmlb** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- board/mistify/rootfs_overlay/etc/shadow @ r3

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/109)

**Comment by mmlb** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- package/mistify/openvswitch/0003-datapath-do-not-add-vlan_hwaccel_push_inside-for-ker.patch @ r4

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/109)

**Comment by mmlb** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- configs/mistify_defconfig @ r5
- package/mistify/openvswitch/openvswitch.mk @ r5

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/109)

**Comment by trisk** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- board/mistify/rootfs_overlay/etc/shadow @ r3
- configs/mistify_defconfig @ r5
- package/mistify/openvswitch/0003-datapath-do-not-add-vlan_hwaccel_push_inside-for-ker.patch @ r4
- package/mistify/openvswitch/openvswitch.mk @ r5

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/109)

**Comment by StevenIsaacs** [comment]
Reviewed 7 of 7 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[package/mistify/openvswitch/0003-datapath-do-not-add-vlan_hwaccel_push_inside-for-ker.patch, line 1 \[r5\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/109#-JrstoD4JYyxyLUybLnM)** ([raw file](https://github.com/mistifyio/mistify-os/blob/2aadfd535d307d609c50f79be60f589ce8c0a91b/package/mistify/openvswitch/0003-datapath-do-not-add-vlan_hwaccel_push_inside-for-ker.patch#L1)):</sup>
This is already in master. Shouldn't be a problem though.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/109)

**Pull request merged**
