### PR TITLE
Rename last log symlink to $logdir/buildroot.log and create earlier

### PR DESCRIPTION
**Pull request by trisk**
Trivial change.

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-os/113)

### CODE REVIEW

**Comment by StevenIsaacs** [comment]
<sup>**[buildmistify, line 709 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/113#-JsRFG_izbnUL-I0b7aY)** ([raw file](https://github.com/mistifyio/mistify-os/blob/9b475214b5569dea89715673fcdd3b127c047f27/buildmistify#L709)):</sup>
This is not a valid symlink until after the $logfile has been created. Perhaps after the 'rc=' ?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/113)

**Comment by mmlb** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/113)

**Comment by trisk** [comment]
It is immediately created afterward (i.e., it's not really likely we'll be interrupted before that), but since we get the output on stdout also we can just move it. Just worried about Ctrl-C.

**Comment by StevenIsaacs** [comment]
Ok, I can understand your concern about ctrl-c. The log file is there in either case. LGTM.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/113)

**Comment by StevenIsaacs** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/113)

**Pull request merged**
