### PR TITLE
Collapse --buildrootbranch and --buildroottag options into single --buildrootversion along with corresponding testscript changes.

### PR DESCRIPTION
**Pull request by StevenIsaacs**
This PR covers a few changes.
- The buildmistify script has been modified to collapse the --buildrootbranch and --buildroottag options into a single option, --buildrootversion, similar to what was done previously with the toolchain install.
- The buildmistify script has been updated to use the get and set build default functions.
- Additional options are now passed to Robot Framework by the testsmistify script to indicate which versions are being tested or built inside a container. The versions being tested do not need to be the same as the versions used by the buildmistify script.
- The build in container test suite has been updated to use the new parameters and some checks have been added to verify mistify related components exist in the target file system.

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-os/112)

### CODE REVIEW

**Comment by trisk** [comment]
<sup>**[buildmistify, line 112 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/112#-Js2FfBVhQ44UNWnoctG)** ([raw file](https://github.com/mistifyio/mistify-os/blob/ed948d18f5804bb43b3b07d87be278ea7dd43807/buildmistify#L112)):</sup>
Any reason for this filename change (no longer matches the option)?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/112)

**Comment by trisk** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/112)

**Comment by StevenIsaacs** [comment]
<sup>**[buildmistify, line 112 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/112#-Js2FfBVhQ44UNWnoctG)** ([raw file](https://github.com/mistifyio/mistify-os/blob/ed948d18f5804bb43b3b07d87be278ea7dd43807/buildmistify#L112)):</sup>
Some legacy. The change was to be consistent with the variables and be more explicit. There's another file which changed from 'config' to 'mistifycfg' (above)  which triggered this thinking.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/112)

**Comment by trisk** [comment]
<sup>**[buildmistify, line 112 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/112#-Js2FfBVhQ44UNWnoctG)** ([raw file](https://github.com/mistifyio/mistify-os/blob/ed948d18f5804bb43b3b07d87be278ea7dd43807/buildmistify#L112)):</sup>
I was guessing 'mistifycfg' was renamed from 'config' due to a namespace conflict, but the variable and option name here is is still 'kconfig', unless I'm missing something... and we still have 'bbconfig' and 'tcconfig' below.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/112)

**Comment by StevenIsaacs** [comment]
<sup>**[buildmistify, line 112 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/112#-Js2FfBVhQ44UNWnoctG)** ([raw file](https://github.com/mistifyio/mistify-os/blob/ed948d18f5804bb43b3b07d87be278ea7dd43807/buildmistify#L112)):</sup>
Ah, good point about bbconfig and tcconfig. I'll change it back.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/112)

**Comment by StevenIsaacs** [comment]
<sup>**[buildmistify, line 112 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/112#-Js2FfBVhQ44UNWnoctG)** ([raw file](https://github.com/mistifyio/mistify-os/blob/ed948d18f5804bb43b3b07d87be278ea7dd43807/buildmistify#L112)):</sup>
So, for better consistency how about --mconfig, --kconfig and --bbconfig for these options, file names and variable names?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/112)

**Comment by trisk** [comment]
<sup>**[buildmistify, line 112 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/112#-Js2FfBVhQ44UNWnoctG)** ([raw file](https://github.com/mistifyio/mistify-os/blob/ed948d18f5804bb43b3b07d87be278ea7dd43807/buildmistify#L112)):</sup>
Sounds good to me!

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/112)

**Comment by mmlb** [comment]
Reviewed 6 of 6 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[buildmistify, line 75 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/112#-Js280gXHcDVC1Dc0E1k)** ([raw file](https://github.com/mistifyio/mistify-os/blob/ed948d18f5804bb43b3b07d87be278ea7dd43807/buildmistify#L75)):</sup>
s/branch name/version info/

---

<sup>**[buildmistify, line 318 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/112#-Js28crFMuDm4RHoq7t-)** ([raw file](https://github.com/mistifyio/mistify-os/blob/ed948d18f5804bb43b3b07d87be278ea7dd43807/buildmistify#L318)):</sup>
do we want to handle go{version,dir}/toolchain{version,dir} here too?

---

<sup>**[buildmistify, line 330 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/112#-Js28tDS8RkRpQOEk9kU)** ([raw file](https://github.com/mistifyio/mistify-os/blob/ed948d18f5804bb43b3b07d87be278ea7dd43807/buildmistify#L330)):</sup>
should this TODO be reworded to use buildrootversion?

---

<sup>**[buildmistify, line 333 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/112#-Js7MLk0aIxv_aiM9i8f)** ([raw file](https://github.com/mistifyio/mistify-os/blob/b5ab8ccdf2efc2dde0e8541b6cde6af4ed4cf967/buildmistify#L333)):</sup>
hmmm why not rename this var to `buildrooturidefault`to match the other buildroot vars?

---

<sup>**[test/testcases/BuildMistify.robot, line 74 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/112#-Js2A2dpH_AISu534RfB)** ([raw file](https://github.com/mistifyio/mistify-os/blob/ed948d18f5804bb43b3b07d87be278ea7dd43807/test/testcases/BuildMistify.robot#L74)):</sup>
missing nfirewalld and mistify-image-service

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/112)

**Comment by StevenIsaacs** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[buildmistify, line 75 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/112#-Js280gXHcDVC1Dc0E1k)** ([raw file](https://github.com/mistifyio/mistify-os/blob/ed948d18f5804bb43b3b07d87be278ea7dd43807/buildmistify#L75)):</sup>
Done.

---

<sup>**[buildmistify, line 318 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/112#-Js28crFMuDm4RHoq7t-)** ([raw file](https://github.com/mistifyio/mistify-os/blob/ed948d18f5804bb43b3b07d87be278ea7dd43807/buildmistify#L318)):</sup>
I don't think so. What's really needed is a reset of go options like with --toolchainreset but --goreset instead.

---

<sup>**[buildmistify, line 330 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/112#-Js28tDS8RkRpQOEk9kU)** ([raw file](https://github.com/mistifyio/mistify-os/blob/ed948d18f5804bb43b3b07d87be278ea7dd43807/buildmistify#L330)):</sup>
Done. Good catch.

---

<sup>**[buildmistify, line 333 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/112#-Js7MLk0aIxv_aiM9i8f)** ([raw file](https://github.com/mistifyio/mistify-os/blob/b5ab8ccdf2efc2dde0e8541b6cde6af4ed4cf967/buildmistify#L333)):</sup>
Done. No good reason not to.

---

<sup>**[test/testcases/BuildMistify.robot, line 74 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/112#-Js2A2dpH_AISu534RfB)** ([raw file](https://github.com/mistifyio/mistify-os/blob/ed948d18f5804bb43b3b07d87be278ea7dd43807/test/testcases/BuildMistify.robot#L74)):</sup>
I see a usr/sbin/cfirewalld instead of nfirewalld. I was holding back until the name changes.

I added usr/sbin/mistify-image-service.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/112)

**Comment by trisk** [comment]
<sup>**[buildmistify, line 75 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/112#-Js280gXHcDVC1Dc0E1k)** ([raw file](https://github.com/mistifyio/mistify-os/blob/ed948d18f5804bb43b3b07d87be278ea7dd43807/buildmistify#L75)):</sup>
Still says "branch name" on the right?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/112)

**Comment by mmlb** [comment]
Review status: 4 of 6 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[buildmistify, line 318 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/112#-Js28crFMuDm4RHoq7t-)** ([raw file](https://github.com/mistifyio/mistify-os/blob/ed948d18f5804bb43b3b07d87be278ea7dd43807/buildmistify#L318)):</sup>
ahhh yeah makes sense, I took $resetdefaults == { buildroot, go, toolchain}

---

<sup>**[test/testcases/BuildMistify.robot, line 74 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/112#-Js2A2dpH_AISu534RfB)** ([raw file](https://github.com/mistifyio/mistify-os/blob/ed948d18f5804bb43b3b07d87be278ea7dd43807/test/testcases/BuildMistify.robot#L74)):</sup>
yup lochness/lochness.mk is still at an older version. Lets hold off on rolling that update in until all the packages can be updated.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/112)

**Comment by mmlb** [comment]
Reviewed 1 of 2 files at r3.
Review status: 5 of 6 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/112)

**Comment by StevenIsaacs** [comment]
<sup>**[buildmistify, line 75 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/112#-Js280gXHcDVC1Dc0E1k)** ([raw file](https://github.com/mistifyio/mistify-os/blob/ed948d18f5804bb43b3b07d87be278ea7dd43807/buildmistify#L75)):</sup>
oh, duh -- done

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/112)

**Comment by mmlb** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/112)

**Comment by trisk** [comment]
Reviewed 2 of 2 files at r3, 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/112)

**Pull request merged**
