### PR TITLE
Mistify update for Buildroot 2015.11

### PR DESCRIPTION
**Pull request by daleghent**
This brings `mistify-os` in-line with Buildroot 2015.11. We remove our local `skeleton` directory to use Buildroot's, with some changes to the structure of `/var` made in the `mistify-post-build` script.

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-os/155)

### CODE REVIEW

**Comment by trisk** [comment]
*[board/mistify/rootfs_overlay/usr/lib/systemd/system/getty.target.wants/gett@tty1.service, line 1 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/155#-K6jGTnKV7P0lpG9_qLH:-K6jGTnMmL-4GF_r2M-H:462718586) ([raw file](https://github.com/mistifyio/mistify-os/blob/5c1ffd421eb9c5b67b7be41ba2d5174b6de6190e/board/mistify/rootfs_overlay/usr/lib/systemd/system/getty.target.wants/gett@tty1.service#L1)):*
Typo in this filename (gett@).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/155)*

**Comment by trisk** [comment]
Reviewed 63 of 63 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/155)*

**Comment by daleghent** [comment]
*[board/mistify/rootfs_overlay/usr/lib/systemd/system/getty.target.wants/getty@tty1.service, line 1 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/155#-K6jGTnKV7P0lpG9_qLH:-K6jLwmQszvxvx2Rb0Mc:-82894076) ([raw file](https://github.com/mistifyio/mistify-os/blob/5c1ffd421eb9c5b67b7be41ba2d5174b6de6190e/board/mistify/rootfs_overlay/usr/lib/systemd/system/getty.target.wants/getty@tty1.service#L1)):*
Corrected

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/155)*

**Comment by daleghent** [comment]
*[board/mistify/rootfs_overlay/usr/lib/systemd/system/getty.target.wants/getty@tty1.service, line 1 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/155#-K6jGTnKV7P0lpG9_qLH:-K6jM0W92EkOqyIyu3sT:-499146009) ([raw file](https://github.com/mistifyio/mistify-os/blob/5c1ffd421eb9c5b67b7be41ba2d5174b6de6190e/board/mistify/rootfs_overlay/usr/lib/systemd/system/getty.target.wants/getty@tty1.service#L1)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/155)*

**Comment by trisk** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/155)*

**Comment by mmlb** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[scripts/mistify-post-build, line 109 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/155#-K6jaOLYGwVGSI67P330:-K6jaOLYGwVGSI67P331:-166937449) ([raw file](https://github.com/mistifyio/mistify-os/blob/7eec09eb3a767108a53f603d0806cbcb7648851f/scripts/mistify-post-build#L109)):*
FYI can be minimized to ```
for i in $targetdir/var/{cache,lock,log,spool,tmp}; do
```
your call

---

*[scripts/mistify-post-build, line 116 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/155#-K6jajsrCSBod9uHTT1v:-K6jajss_0tmMLkaWxcJ:-694050163) ([raw file](https://github.com/mistifyio/mistify-os/blob/7eec09eb3a767108a53f603d0806cbcb7648851f/scripts/mistify-post-build#L116)):*
isn't this unnecessary, or maybe should go before the loop? If `/var` doesn't exist at this point then the loop would have failed, but then how were there symlinks there to begin with...

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/155)*
<!-- Sent from Reviewable.io -->

**Comment by mmlb** [comment]
Reviewed 62 of 64 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/155)*

**Comment by mmlb** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[scripts/mistify-post-build, line 109 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/155#-K6jaOLYGwVGSI67P330:-K6jbUNaDOj0GiZBDoLu:-329242093) ([raw file](https://github.com/mistifyio/mistify-os/blob/7eec09eb3a767108a53f603d0806cbcb7648851f/scripts/mistify-post-build#L109)):*
hmm not sure why reviewable marked previous comment as resolved.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/155)*

**Comment by mmlb** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[scripts/mistify-post-build, line 109 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/155#-K6jaOLYGwVGSI67P330:-K6jbfewE12GF0c_iLA8:658692745) ([raw file](https://github.com/mistifyio/mistify-os/blob/7eec09eb3a767108a53f603d0806cbcb7648851f/scripts/mistify-post-build#L109)):*
Lets try this again, can be changed to
```
for i in $targetdir/var/{cache,lock,log,spool,tmp}; do
```
your call if you want to do it or not

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/155)*

**Comment by daleghent** [comment]
*[scripts/mistify-post-build, line 109 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/155#-K6jaOLYGwVGSI67P330:-K6oNXIzA21cRt076t2O:128457003) ([raw file](https://github.com/mistifyio/mistify-os/blob/7eec09eb3a767108a53f603d0806cbcb7648851f/scripts/mistify-post-build#L109)):*
I'll keep the current format as-is for readability/editing reasons. In the future if we need to add or remove a item to that list, it'll be more apparent in the diff what is going on.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/155)*

**Comment by mmlb** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[scripts/mistify-post-build, line 116 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/155#-K6jajsrCSBod9uHTT1v:-K6oOQqJ5TrHfej5BHqL:273277713) ([raw file](https://github.com/mistifyio/mistify-os/blob/7eec09eb3a767108a53f603d0806cbcb7648851f/scripts/mistify-post-build#L116)):*
Why is reviewable marking all my comments as "Resolved" :sigh: Please see ^

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/155)*

**Comment by mmlb** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/155)*

**Comment by daleghent** [comment]
*[scripts/mistify-post-build, line 116 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/155#-K6jajsrCSBod9uHTT1v:-K6spmkP0CzhT0CWvgAJ:-1128864674) ([raw file](https://github.com/mistifyio/mistify-os/blob/7eec09eb3a767108a53f603d0806cbcb7648851f/scripts/mistify-post-build#L116)):*
`/var` is a directory, and buildroot's default skel has `/var/lock` and `/var/spool` in particular as symlinks to `/tmp` which is nuked in the `for` loop and replaced with those directories.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/155)*

**Comment by daleghent** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[board/mistify/rootfs_overlay/usr/lib/systemd/system/getty.target.wants/getty@tty1.service, line 1 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/155#-K6jGTnKV7P0lpG9_qLH:-K6sqzQ6RnLrDPbd9qEj:-499146009) ([raw file](https://github.com/mistifyio/mistify-os/blob/5c1ffd421eb9c5b67b7be41ba2d5174b6de6190e/board/mistify/rootfs_overlay/usr/lib/systemd/system/getty.target.wants/getty@tty1.service#L1)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/155)*

**Pull request merged**
