### PR TITLE
Refresh hashes

### PR DESCRIPTION
**Pull request by mmlb**
[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-os/157)

### CODE REVIEW

**Comment by mmlb** [comment]
Ok to test.

**Comment by mmlb** [comment]
Ok to test

**Comment by mmlb** [comment]
Ok to test

**Comment by StevenIsaacs** [comment]
Reviewed 8 of 8 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/157)*

**Pull request merged**
