### PR TITLE
MIST-510 Etcd cluster bootstrapping and long-term health

### PR DESCRIPTION
**Pull request by TauZero**
The old method of starting etcd on hv0, building a new cluster on hv1
and hv2, wiping and joining hv0 to the new cluster, and repopulating the
data was leading to inconsistent and often failing cluster
initialization in some environments. Instead, simply update the hv0 node
and then join hv1 and hv2 to it. This leads to more consistent results.

The heartbeat interval and election timeout have been increased, which
appears to have helped with the stability of the cluster once it is running.

In the process, code has been refactored into functions grouping related
actions for clarity. Logging has also been improved to cover start and
end of functions and major commands, as well as include a stack of
function:lineno for better identification.

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-os/134)

### CODE REVIEW

**Comment by TauZero** [comment]
Ok to test

**Comment by TauZero** [comment]
Ok to test

**Comment by mmlb** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[board/mistify/rootfs_overlay/root/cluster-init, line 182 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/134#-JwciNCvAwkwDC6IBsqF)** ([raw file](https://github.com/mistifyio/mistify-os/blob/ed85df44ae535a04d4cba66f8fda406bbe8482df/board/mistify/rootfs_overlay/root/cluster-init#L182)):</sup>
Hmm I think this should be a cluster wide setting not per hv. That could probably lead to pretty weird situations.

Also, this should probably be added to `cluster-init-config` since this is supposed to be to take into account network latencies and such. But since we don't yet have a tool to modify the cluster wide config this should not be hard-coded here.

---

<sup>**[board/mistify/rootfs_overlay/root/cluster-init, line 231 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/134#-JwcjygDXZfyHVZt-S1E)** ([raw file](https://github.com/mistifyio/mistify-os/blob/ed85df44ae535a04d4cba66f8fda406bbe8482df/board/mistify/rootfs_overlay/root/cluster-init#L231)):</sup>
is this etcd's old port or the new one I cant remember?

---

<sup>**[board/mistify/rootfs_overlay/root/cluster-init, line 250 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/134#-JwckDJ5iDhhQVoAb59b)** ([raw file](https://github.com/mistifyio/mistify-os/blob/ed85df44ae535a04d4cba66f8fda406bbe8482df/board/mistify/rootfs_overlay/root/cluster-init#L250)):</sup>
just fyi this could have been written as a block statement ```sh
{
    local i
    for (( i=0; i < $NODE_COUNT; i++ )); do
        echo "$nameserver ${ips[$i]}"
    done
} > /etc/resolv.conf
```

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/134)
<!-- Sent from Reviewable.io -->

**Comment by TauZero** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[board/mistify/rootfs_overlay/root/cluster-init, line 231 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/134#-JwcjygDXZfyHVZt-S1E)** ([raw file](https://github.com/mistifyio/mistify-os/blob/ed85df44ae535a04d4cba66f8fda406bbe8482df/board/mistify/rootfs_overlay/root/cluster-init#L231)):</sup>
New one, I believe. It's what's discussed in the master documentation (also works with etcd 2.1.x)

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/134)

**Comment by TauZero** [comment]
Review status: 1 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[board/mistify/rootfs_overlay/root/cluster-init, line 182 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/134#-JwciNCvAwkwDC6IBsqF)** ([raw file](https://github.com/mistifyio/mistify-os/blob/ed85df44ae535a04d4cba66f8fda406bbe8482df/board/mistify/rootfs_overlay/root/cluster-init#L182)):</sup>
Moved values to cluster-init-config. Moved set to the general lochness cluster config.

---

<sup>**[board/mistify/rootfs_overlay/root/cluster-init, line 250 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/134#-JwckDJ5iDhhQVoAb59b)** ([raw file](https://github.com/mistifyio/mistify-os/blob/ed85df44ae535a04d4cba66f8fda406bbe8482df/board/mistify/rootfs_overlay/root/cluster-init#L250)):</sup>
Updated.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/134)

**Comment by mmlb** [comment]
Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/134)

**Pull request merged**
