### PR TITLE
Update to Buildroot 2015.08

### PR DESCRIPTION
**Pull request by daleghent**
[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-os/145)

### CODE REVIEW

**Comment by StevenIsaacs** [comment]
<sup>**[buildmistify, line 742 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/145#-JyEMirX73NBXv6ifTRp)** ([raw file](https://github.com/mistifyio/mistify-os/blob/c10f52e7a2b6aad548ec051618538d23f47c704d/buildmistify#L742)):</sup>
Backward compatibility between buildmistify and prior versions of buildroot? I suppose it's OK as long as everything moves forward (no attempt to use a prior tag etc.).

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/145)

**Comment by daleghent** [comment]
<sup>**[buildmistify, line 742 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/145#-JyEMirX73NBXv6ifTRp)** ([raw file](https://github.com/mistifyio/mistify-os/blob/c10f52e7a2b6aad548ec051618538d23f47c704d/buildmistify#L742)):</sup>
We never really guaranteed backwards compatibility. mistify-os and buildroot have always been in lockstep synchronization 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/145)

**Comment by StevenIsaacs** [comment]
<sup>**[configs/mistify_defconfig, line 277 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/145#-JyERD7owE1aGI2Pxvz_)** ([raw file](https://github.com/mistifyio/mistify-os/blob/c10f52e7a2b6aad548ec051618538d23f47c704d/configs/mistify_defconfig#L277)):</sup>
We want the kernel in the /boot directory of the initrd?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/145)

**Comment by daleghent** [comment]
<sup>**[configs/mistify_defconfig, line 0 \[r1\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/145#-JyERD7owE1aGI2Pxvz_)** ([raw file](https://github.com/mistifyio/mistify-os/blob/c10f52e7a2b6aad548ec051618538d23f47c704d/configs/mistify_defconfig#L0)):</sup>
It's now needed for booting off the ISO with GRUB enabled. At only 5.3MB in size, it's not a terrible addition. It also is nice to have the static kernel packaged in the same image that contains its modules.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/145)

**Comment by TauZero** [comment]
Reviewed 7 of 12 files at r1.
Review status: 7 of 12 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/145)

**Comment by TauZero** [comment]
Reviewed 5 of 12 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/145)

**Pull request merged**
