### PR TITLE
Kernel 4.0.7

### PR DESCRIPTION
**Pull request by daleghent**
[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-os/126)

### CODE REVIEW

**Comment by StevenIsaacs** [comment]
Reviewed 9 of 10 files at r1.
Review status: 9 of 10 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/126)

**Comment by StevenIsaacs** [comment]
Reviewed 1 of 10 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/126)

**Comment by rizvfe00** [comment]
Ok to test

**Comment by trisk** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/126)

**Pull request merged**
