### PR TITLE
MIST-484 Moar nodes

### PR DESCRIPTION
**Pull request by mmlb**
General cleanups and removal of racy/non-determenisms.

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-os/127)

### CODE REVIEW

**Comment by StevenIsaacs** [comment]
Reviewed 1 of 1 files at r1.
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/127)

**Comment by TauZero** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/127)

**Comment by daleghent** [comment]
Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/127)

**Comment by mmlb** [comment]
ok to test

**Comment by TauZero** [comment]
Reviewed 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/127)

**Comment by mmlb** [comment]
Ok to test

**Pull request merged**
