### PR TITLE
User namespace support for Docker

### PR DESCRIPTION
**Pull request by trisk**
This updates Docker to a recent version from the master branch, replaces the zfs graphdriver, and adds the user namespace support implementation from https://github.com/docker/docker/pull/12648 and enables remapped root user/group for containers.

Can be used with `docker run --device=/dev/zfs:/dev/zfs ...` and a container image with ZFS userspace utilities for testing `zfs allow dockroot ...`.

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-os/104)

### CODE REVIEW

**Comment by mmlb** [comment]
@trisk I'm getting this when trying to build

```
./capabilities_linux.go:52: undefined: capability.CAP_AUDIT_READ
./standard_init_linux.go:93: pdeath.Restore undefined (type int has no field or method Restore)
make[1]: *** [direct-build] Error 2
make[1]: Leaving directory `/home/ubuntu/mistify-os/build/mistify/base/tmp/GOPATH/src/github.com/docker/libcontainer'
make: *** [/home/ubuntu/mistify-os/build/mistify/base/build/libcontainer-a4a648ce3016ad7a5d0bb40359ec2ca81aa7640c/.stamp_built] Error 2
make: Leaving directory `/home/ubuntu/buildroot'

```

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/104)

**Comment by mmlb** [comment]
Issue was on my side, so fully LGTM! :+1: 

---

Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/104)

**Comment by TauZero** [comment]
Review status: :shipit: all files reviewed, all discussions resolved, all commit checks successful.
Reviewed files:
- package/mistify/docker-docker/docker-docker.mk @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/104)

**Comment by trisk** [comment]
Ack, thought I pushed this already, but it turns out it was stuck in my local fork.

**Comment by trisk** [comment]
Nevermind, GitHub was lying to me.

**Pull request closed without merging**
