### PR TITLE
MIST-505 OVS subagent and ovs libvirt/kvm integration

### PR DESCRIPTION
**Pull request by TauZero**
Adds mistify-agent-ovs and updates such that libvirt kvm guests use ovs for network interfaces.

Slightly incomplete, but wanted to put up so people can start reviewing what is here.
Before merging, make sure PR includes setup of `mistify0` ovs bridge

[Review on Reviewable](https://reviewable.io/reviews/mistifyio/mistify-os/129)

### CODE REVIEW

**Comment by mmlb** [comment]
Reviewed 6 of 7 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[package/mistify/mistify-agent-ovs/mistify-agent-ovs.service, line 1 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/129#-JuwvNE6sAGdBbedUraT)** ([raw file](https://github.com/mistifyio/mistify-os/blob/73f38cac718e6a159c4a310ab244e80efdc695af/package/mistify/mistify-agent-ovs/mistify-agent-ovs.service#L1)):</sup>
Is this file actually needed, lochness-ansible should take care of this. Also this is setup for mistify-agent-docker not ovs ...

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/129)

**Comment by TauZero** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[package/mistify/mistify-agent-ovs/mistify-agent-ovs.service, line 1 \[r2\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/129#-JuwvNE6sAGdBbedUraT)** ([raw file](https://github.com/mistifyio/mistify-os/blob/73f38cac718e6a159c4a310ab244e80efdc695af/package/mistify/mistify-agent-ovs/mistify-agent-ovs.service#L1)):</sup>
Arg. I thought I removed this. Yes, the service file is in lochness-ansible. Removed.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/129)

**Comment by mmlb** [comment]
Reviewed 1 of 3 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/129)

**Comment by TauZero** [comment]
The mistify0 bridge is now getting set up correctly.

---

Review status: 9 of 18 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/129)

**Comment by daleghent** [comment]
Reviewed 9 of 9 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/129)

**Comment by mmlb** [comment]
Reviewed 1 of 5 files at r2, 9 of 9 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[board/mistify/rootfs_overlay/etc/pre-init.d/net-init.sh, line 97 \[r4\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/129#-JvVsLkFAa2IMwWF2KQH)** ([raw file](https://github.com/mistifyio/mistify-os/blob/dd7ff7ede2bafabf9fd9ea744e0a13f2e848297a/board/mistify/rootfs_overlay/etc/pre-init.d/net-init.sh#L97)):</sup>
Why did you remove the check for existence? I wanted to avoid the (possibly non-realistic) situation of multiple interfaces both able to get dhcp possibly differing across boots.

---

<sup>**[package/mistify/openvswitch/40-openvswitch.rules, line 2 \[r4\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/129#-JvVu1VVaopZjRbq6xCU)** ([raw file](https://github.com/mistifyio/mistify-os/blob/dd7ff7ede2bafabf9fd9ea744e0a13f2e848297a/package/mistify/openvswitch/40-openvswitch.rules#L2)):</sup>
hmm though `PROGRAM` may work here, its not the correct action. You want `RUN` and to add it to the list of RUN actions via `RUN+=/usr/...`. PROGRAM is meant for device naming and there is no guarantee the device node even exists yet. RUN is specifically to run something as a reaction to the device being modified.

---

<sup>**[package/mistify/openvswitch/ovsbridge.service, line 8 \[r4\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/129#-JvVt5FyIcIoa5GaJZg5)** ([raw file](https://github.com/mistifyio/mistify-os/blob/dd7ff7ede2bafabf9fd9ea744e0a13f2e848297a/package/mistify/openvswitch/ovsbridge.service#L8)):</sup>
This service will fail if .ifsate does not exist, is this wanted?

---

<sup>**[package/mistify/openvswitch/ovsbridge.service, line 11 \[r4\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/129#-JvVtXISuQUPJvifRTl1)** ([raw file](https://github.com/mistifyio/mistify-os/blob/dd7ff7ede2bafabf9fd9ea744e0a13f2e848297a/package/mistify/openvswitch/ovsbridge.service#L11)):</sup>
Probably want to filter this down a little bit with `--subsytem-match=net` and possibly also to the names to ensure that only devs that will match filter are triggered.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/129)

**Comment by TauZero** [comment]
Review status: 16 of 18 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[board/mistify/rootfs_overlay/etc/pre-init.d/net-init.sh, line 97 \[r4\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/129#-JvVsLkFAa2IMwWF2KQH)** ([raw file](https://github.com/mistifyio/mistify-os/blob/dd7ff7ede2bafabf9fd9ea744e0a13f2e848297a/board/mistify/rootfs_overlay/etc/pre-init.d/net-init.sh#L97)):</sup>
The interface state file gets reinitialized (the mac isn't getting stored in a netdev file after the first good boot) so it won't have a MACAddress in it yet.

---

<sup>**[package/mistify/openvswitch/40-openvswitch.rules, line 2 \[r4\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/129#-JvVu1VVaopZjRbq6xCU)** ([raw file](https://github.com/mistifyio/mistify-os/blob/dd7ff7ede2bafabf9fd9ea744e0a13f2e848297a/package/mistify/openvswitch/40-openvswitch.rules#L2)):</sup>
Done

---

<sup>**[package/mistify/openvswitch/ovsbridge.service, line 8 \[r4\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/129#-JvVt5FyIcIoa5GaJZg5)** ([raw file](https://github.com/mistifyio/mistify-os/blob/dd7ff7ede2bafabf9fd9ea744e0a13f2e848297a/package/mistify/openvswitch/ovsbridge.service#L8)):</sup>
It gets created by the pre-init on boot.

---

<sup>**[package/mistify/openvswitch/ovsbridge.service, line 11 \[r4\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/129#-JvVtXISuQUPJvifRTl1)** ([raw file](https://github.com/mistifyio/mistify-os/blob/dd7ff7ede2bafabf9fd9ea744e0a13f2e848297a/package/mistify/openvswitch/ovsbridge.service#L11)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/129)

**Comment by mmlb** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[board/mistify/rootfs_overlay/etc/pre-init.d/net-init.sh, line 97 \[r4\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/129#-JvVsLkFAa2IMwWF2KQH)** ([raw file](https://github.com/mistifyio/mistify-os/blob/dd7ff7ede2bafabf9fd9ea744e0a13f2e848297a/board/mistify/rootfs_overlay/etc/pre-init.d/net-init.sh#L97)):</sup>
Hmm I guess I'm wondering why you don't save the mac to a file and use that in the service instead of .ifstate? This way first good boot will save the mac, and ovs on this node will always have the same mac.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/129)

**Comment by TauZero** [comment]
Review status: 15 of 19 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[board/mistify/rootfs_overlay/etc/pre-init.d/net-init.sh, line 97 \[r4\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/129#-JvVsLkFAa2IMwWF2KQH)** ([raw file](https://github.com/mistifyio/mistify-os/blob/dd7ff7ede2bafabf9fd9ea744e0a13f2e848297a/board/mistify/rootfs_overlay/etc/pre-init.d/net-init.sh#L97)):</sup>
Moved to a separate file that will persist. 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/129)

**Comment by mmlb** [comment]
Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[package/mistify/openvswitch/ovsbridge, line 1 \[r6\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/129#-JvpAwRUymD7_SnauGr-)** ([raw file](https://github.com/mistifyio/mistify-os/blob/219f2b2cfe48a5d550b2a8cda6e163474a326610/package/mistify/openvswitch/ovsbridge#L1)):</sup>
Umm is this the wrong file? systemd will not execute any statement here.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/129)

**Comment by mmlb** [comment]
Reviewed 1 of 1 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/129)

**Comment by mmlb** [comment]
Reviewed 1 of 4 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/129)

**Comment by TauZero** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[package/mistify/openvswitch/ovsbridge, line 1 \[r6\]](https://reviewable.io:443/reviews/mistifyio/mistify-os/129#-JvpAwRUymD7_SnauGr-)** ([raw file](https://github.com/mistifyio/mistify-os/blob/219f2b2cfe48a5d550b2a8cda6e163474a326610/package/mistify/openvswitch/ovsbridge#L1)):</sup>
Had forgotten to carry over live changes to the service file to the repo. The service will call this instead of doing a bunch of individual execstarts

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/129)

**Comment by TauZero** [comment]
Ok to build

**Comment by TauZero** [comment]
Ok to test

**Comment by trisk** [comment]
Reviewed 1 of 9 files at r4, 1 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/mistifyio/mistify-os/129)

**Pull request merged**
